### PR TITLE
Add config option to disable for fishing

### PR DESCRIPTION
**Pull request by Iiridayn**
Possible resolution for #54 - working well enough for me.

### CODE REVIEW

**Comment by ThePhilderbeast** [comment]
this needs work, there is much more to be done to add another toggle including adding it to the commands and GUI

**Comment by Iiridayn** [comment]
I based it on AutoMob, which also has no GUI options (didn't realize there were commands). Honestly, if you'd like to expose AutoMob to the GUI instead, I could just disable that when fishing.

**Comment by ThePhilderbeast** [comment]
that sounds like a good solution to me.

**Comment by Iiridayn** [comment]
Kk, I'll cancel this and look forward to it :).

**Pull request closed without merging**
